sudo: required
language: python
python: 3.5

services:
- docker

install:
- pip install -r requirements.txt
- python setup.py build_ext --inplace

script:
- mkdir -p ~/.config/jd4 && cp examples/config.yaml ~/.config/jd4/
- python -m unittest -v jd4.case_test jd4.compare_test
- docker build -t vijos/jd4 .
- docker run --privileged
      -v $(readlink -f examples/config.yaml):/root/.config/jd4/config.yaml
      vijos/jd4 /bin/bash -c "source /venv/bin/activate &&
                              python3 -m unittest -v jd4.integration_test"
